sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update --system
before_script: bundle update
script: script/cibuild
exclude: [vendor]
notifications:
  email:
    - recipients:
      - wgraham@clir.org
    on_success: never # default: change
    on_failure: always # default: always
